### ISSUE TITLE
Implement a default help message on the base API URL `sucuri.../` 

### ISSUE THREAD

**Issue by abhi18av** [biosharp-dotnet/sucuri-api#15]
We need to change the current default message to print a usage doc. 

```html
<html style='background-color: #01b0c4; overflow-y: hidden'>

    <head>
        <title>500</title>
        <meta charset='utf-8'>
    </head>

    <body style='color: white; font-family: Helvetica,Arial,sans-serif;'>

        <div style='padding: 4em; text-align: center'>
            <p style='font-size: 3em;
                margin: 0;
                margin-top: 1.5em;
                margin-bottom: 0.5em;'>
                ⚠️ 
                Internal Server Error
            </p>
            <hr style='border-style: solid; width: 50%;' />
            <p style='font-size: 10em; margin: 0;'>
                500
            </p>
            <p style='font-size: 1.3em;'>
                http://localhost:8085/
            </p>

            
        </div>

        <p style='text-align: center;
            width: 100%;
            font-size: 0.9em;
            position: fixed;
            bottom: 0px;'>
            🧡 Powered by <a href='https://badgerati.github.io/Pode/' style='color: wheat; text-decoration: none;'>Pode</a>
        </p>

    </body>

</html>



```

**Comment by Aryan-sharma11** [comment]
> We need to change the current default message to print a usage doc.
> 
> ```
> <html style='background-color: #01b0c4; overflow-y: hidden'>
> 
>     <head>
>         <title>500</title>
>         <meta charset='utf-8'>
>     </head>
> 
>     <body style='color: white; font-family: Helvetica,Arial,sans-serif;'>
> 
>         <div style='padding: 4em; text-align: center'>
>             <p style='font-size: 3em;
>                 margin: 0;
>                 margin-top: 1.5em;
>                 margin-bottom: 0.5em;'>
>                 ⚠️ 
>                 Internal Server Error
>             </p>
>             <hr style='border-style: solid; width: 50%;' />
>             <p style='font-size: 10em; margin: 0;'>
>                 500
>             </p>
>             <p style='font-size: 1.3em;'>
>                 http://localhost:8085/
>             </p>
> 
>             
>         </div>
> 
>         <p style='text-align: center;
>             width: 100%;
>             font-size: 0.9em;
>             position: fixed;
>             bottom: 0px;'>
>             🧡 Powered by <a href='https://badgerati.github.io/Pode/' style='color: wheat; text-decoration: none;'>Pode</a>
>         </p>
> 
>     </body>
> 
> </html>
> ```

Okay, I will work on this, can you suggest what default response we should have? I am thinking of adding some `HTML response` for our base endpoint ( that could also serve as the initial frontend for the service).

**Comment by abhi18av** [comment]
@Aryan-sharma11, I think the default response should be the HTML explaining the input and output of the various Endpoints.

The user doesn't need to know the function level details, just the endpoint.

**Comment by Aryan-sharma11** [comment]
@abhi18av  I think we should close this issue also

**Comment by abhi18av** [comment]
@Aryan-sharma11 , we can close this only when the PR gets merged.

Please link the PR to the issues so that it can automatically be merged :)
