### ISSUE TITLE
[HOLD] Implement redirects for all paths which don't exist ( `/random` -> `/`) 

### ISSUE THREAD

**Issue by abhi18av** [biosharp-dotnet/sucuri-api#16]
HOLD:

I think that pode might actually do this by default.

**Comment by Mxrcon** [comment]
I think that we could do that by modifying how pode treat 404 errors.

Why would we redirect the 404 errors to the root? you'll like to show a specific html content? or to redirect the request and treat it? If the objective is to show a html content we can do it easily [customizing the error page](https://badgerati.github.io/Pode/Tutorials/Routes/Utilities/ErrorPages/)

**Comment by abhi18av** [comment]
> If the objective is to show a html content we can do it easily [customizing the error page](https://badgerati.github.io/Pode/Tutorials/Routes/Utilities/ErrorPages/)

Hmm, this is interesting - could you please confirm what's the current behavior? 

The goal is to redirect visually from wrong/unimplemented URLs like 

/v0/api      => error page
/<random>    => error page
/v1/<random> => error page

**Comment by Mxrcon** [comment]
Currently those requests are redirected to a webpage the "home" that Aryan wrote and shows a message about accessing the docs
