### ISSUE TITLE
Improve the testing for various scenarios

### ISSUE THREAD

**Issue by abhi18av** [biosharp-dotnet/sucuri-api#8]
A first step is to modularize the core (non-pode functions) functions

This module would be imported into the Pode based files and as @Mxrcon , mentioned in the past, we can publish the core module itself.

**Comment by Mxrcon** [comment]
sure, may I take care of this step? I'll have some time today.

**Comment by abhi18av** [comment]
Sure, feel free to take this ahead but please do coordinate with each other :)
